### ISSUE TITLE
Failed to encrypt the data with the generated key: IllegalBlockSizeException: null

### ISSUE THREAD

**Issue by dlazzy** [NiklasMerz/cordova-plugin-fingerprint-aio#83]
## Description

* What did you do : 
Code used (from Paul Halliday) : 

```
this.fingerprintOptions = {
      clientId: "fingerprint-demo",
      clientSecret: "password",
      disableBackup: true
    };

async showFingerprintDialog() {
    try {
      await this.platform.ready();
      const available = await this.fingerprint.isAvailable();
      console.log(available);

      if (available === "OK") {
        const result = await this.fingerprint.show(this.fingerprintOptions);
        console.log(result);
      }
    }
    catch (e) {
      console.error(e);
    }
  }
```

Just try to use the plugin. I'm on Ionic, and there is the `ionic info` result : 

```
cli packages: (/usr/lib/node_modules)

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.8
    Cordova Platforms  : android 6.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v7.8.0
    npm               : 4.2.0 
    OS                : Linux 4.8

Misc:

    backend : pro
```

* What did happen : 
Getting an error when fingerprint is valid : 
`Failed to encrypt the data with the generated key: IllegalBlockSizeException: null`

* What did you expect to happen : 
The plugin need to return a sort of hash

* Type of issue (bug, feature request)
Bug

## Environment

* Plugin version
ionic-native/fingerprint-aio: ^4.5.2
cordova-plugin-fingerprint-aio: ^1.3.4

* Build environment (```cordova info```)
```
Node version: v7.8.0
Cordova version: 7.0.1

config.xml :
<engine name="android" spec="^7.0.0" />
<engine name="ios" spec="^4.5.4" />
<plugin name="cordova-plugin-fingerprint-aio" spec="^1.3.4" />

```

* ```cordova platform ls```
Build on Linux using `ionic cordova run android` to an Android 8

### Logs
`Failed to encrypt the data with the generated key: IllegalBlockSizeException: null`

**Comment by NiklasMerz** [comment]
Thank your for submitting this issue.

I have never tested Android 8. Could you test Android 7? You could also test version 1.3.0 of this plugin which does not include a certain fix. I have to check this myself but my build environment is currently broken. Please report your findings, I will check this soon.

**Comment by dlazzy** [comment]
Thanks for you answer.
I reinstalled the plugin with version `1.3.0`, and it seems to be working on Android 8.
This what I excepted from plugin before, and now it's working : `{withFingerprint: "Is0/g9fTO+TxRdZFmKltLw==↵"}` :)

Unfortunately I don't have an Android 7 to try the last plugin version  (1.3.4)

**Comment by erdem333** [comment]
Still have the same error. 
Samsung Galaxy s8
Android 7.0
Plugin: 1.3.4 / 1.3.0
cordova: 6.5.0 / 7.1.0
cordova-android: 6.2.3
Running in the catch block with a" Failed to encrypt the data with the generated key: IllegalBlockSizeException: null" error response.

**Comment by NiklasMerz** [comment]
@erdem333 Have you tried reinstalling the app?

**Comment by erdem333** [comment]
Problem fixed with newest version of the plugin.

**Comment by nikhiltyagi1991** [comment]
Hi,

Facing the same issue.
One plus 3T
Android 8.0
Plugin: 1.3.4
cordova: 8.0.0
cordova-android: 6.1.2

Steps to recreate:
1. Use fingerprint once (working fine).
2. With app open, add another fingerprint from settings.
3. Return to app try rechecking fingerprint, throws exception.

Done some debugging, error is thrown from tryEncrypt().

**Comment by NiklasMerz** [comment]
You are describing somthing like this #58 

Version v1.3.4 should resolve this.

**Comment by daemons88** [comment]
I use the lasted version of plugin and have the same issue.

happens when I'm in the app and I don't have any registered fingerprints, I go and register while the app is still open, I return to the app, place my fingerprint and give the error: 

Failed to encrypt the data with the generated key: IllegalBlockSizeException: null

**Comment by NiklasMerz** [comment]
Does it work after restarting the app?

**Comment by daemons88** [comment]
In the second try i can login but the i need do that in the first attempt, the clients report that like a error.

maybe it'll fix itself by changing the
 mCipher. init (Cipher. ENCRYPT_MODE, key); 
with this:
OAEPParameterSpec sp = new OAEPParameterSpec("SHA-256", "MGF1", new MGF1ParameterSpec("SHA-1"), PSource.PSpecified.DEFAULT);

https://stackoverflow.com/questions/46042127/android-8-0-illegalblocksizeexception-when-using-rsa-ecb-oaepwithsha-512andmgf1

what do you think?

**Comment by nikhiltyagi1991** [comment]
@NiklasMerz The issue persists after restarting the app. Even restarting the phone doesn't help. After updating fingerprint, it is always throwing IllegalBlockSizeException. Will check further and update.

**Comment by MoPHL** [comment]
Any progress on this issue?

**Comment by NiklasMerz** [comment]
I did not encounter this problem again.

Do you still have this problem regularly? You can try the fix from #81 . I would love to hear your feedback.

**Comment by MoPHL** [comment]
@NiklasMerz We ended up replacing the lines:
´´´
byte[] encrypted = tryEncrypt();
resultJson.put("withFingerprint", Base64.encodeToString(encrypted, 0 /* flags */));
´´´
with:
´´´ resultJson.put("withPassword", true); ´´´

Inside the Fingerprint.java file.
For us this was an acceptable workaround, but I doubt it would make much sense in the repo, so we didn't make any pull with it.

**Comment by NiklasMerz** [comment]
@MoPHL Thank you for this hint. I will have to look deeper into this problem.

**Comment by TalesMattos** [comment]
Same problem in 1.5.0 plugin version. After updating fingerprint (Android 8.0), the authentication in my app does not work: "IllegalBlockSizeException: null".

**Comment by mgarciadash** [comment]
Same here !!
Everything worked fine.
For testing purposes i deleted my fingerpint, then i added a new one.
And now im getting : "Failed to encrypt the data with the generated key: IllegalBlockSizeException: null"

**Comment by NiklasMerz** [comment]
Yes changing the fingerprints in system settings causes this problem. This error needs to be handled like in the original Android plugin.

**Comment by mekery** [comment]
@NiklasMerz 

Same problems, and how to handle this right now?

**Comment by daemons88** [comment]
I don't like the solution I apply, but it works:

What I did was to add in the front a validation that when it comes punctually that error asks him again to enter the fingerprint.

As long as you get the real solution, it works.

**Comment by niconaso** [comment]
> Yes changing the fingerprints in system settings can cause this problem. This error needs to be handled like in the original Android plugin.

Any update on this issue?

**Comment by NiklasMerz** [comment]
This is still unchanged. Unfortunately I don't have time for this at the moment, but I would love to review pull requests for the issue. The original fingerprint plugin for Android should have a patch for this. 

Otherwise this issue has to wait for the biometric prompt update som tjme in the future.

**Comment by developer-dipankar** [comment]
Same problem I'm facing too. How to handle that? It's giving 
**`Failed to encrypt the data with the generated key: IllegalBlockSizeException: null `**
But when I am using "**Use backup**", It's working fine.
Any luck on that? @NiklasMerz

**Comment by NiklasMerz** [comment]
@developer-dipankar I am sorry I did not look into this for some time. Somebody is willing to help may pick it. Unfortunately it could take a while for me to work on this.

**Comment by stephenmacnaughtan** [comment]
Any update on this? I am also facing this problem

**Comment by SafeSahil** [comment]
@NiklasMerz 
I am using the latest version of the plugin (^2.0.0)
Android (8.0.0)
Device (Lenovo K8 Note)
Modal (XT1902-3)

Earlier my application was working perfectly, then
I set one new fingerprint and checked with my application then it started throwing the exception.

But I closed my application and in phone settings -> app -> My app -> Storage
I cleared data and cache storage of my application and then again launched my application and now plugin was able to identify my fingerprint.

(I posted this because I thought that this might help to find some solution)

**Comment by NiklasMerz** [comment]
This problem may disappear after a major rewrite happening in #179 . Feel free to test this version: `cordova plugin add cordova-pluigin-fingerprint-aio@alpha`.

**Comment by NiklasMerz** [comment]
Closed since #179 fixed this issue. Thank you for contributing!
